gameSpecs:
  # MAME game name
  invaders:
    # Ordered file list to load (must be found inside game .zip archive)
    romParts:
      - fileName: invaders.h
        startAddr: 0x0
        expectedSize: 0x800
      - fileName: invaders.g
        startAddr: 0x800
        expectedSize: 0x800
      - fileName: invaders.f
        startAddr: 0x1000
        expectedSize: 0x800
      - fileName: invaders.e
        startAddr: 0x1800
        expectedSize: 0x800
    # Optional: rectangular pixel color overlays (ARGB format)
    colorOverlays:
      - yMin: 32
        yMax: 61
        color: 0xFFFF0000
      - yMin: 184
        yMax: 240
        color: 0xFF00FF00
      - xMin: 16
        xMax: 128
        yMin: 241
        yMax: 256
        color: 0xFF00FF00

    inPorts:
      2:
        - bit: 0 # DIP switch 1: 00 = 3 lives ; 01 = 5 lives
          active: false
        - bit: 1 # DIP switch 2: 10 = 4 lives ; 11 = 6 lives
          active: false
        - bit: 2
          active: false
        - bit: 3
          active: false
        - bit: 7
          active: true

  tst_invd:
    romParts:
      - fileName: test.h
        startAddr: 0x0
        expectedSize: 0x800
      - fileName: invaders.g
        startAddr: 0x800
        expectedSize: 0x800
      - fileName: invaders.f
        startAddr: 0x1000
        expectedSize: 0x800
      - fileName: invaders.e
        startAddr: 0x1800
        expectedSize: 0x800
    colorOverlays:
      - yMin: 32
        yMax: 61
        color: 0xFFFF0000
      - yMin: 184
        yMax: 240
        color: 0xFF00FF00
      - xMin: 16
        xMax: 128
        yMin: 241
        yMax: 256
        color: 0xFF00FF00

  invadpt2:
    romParts:
      - fileName: pv01
        startAddr: 0x0
        expectedSize: 0x800
      - fileName: pv02
        startAddr: 0x800
        expectedSize: 0x800
      - fileName: pv03
        startAddr: 0x1000
        expectedSize: 0x800
      - fileName: pv04
        startAddr: 0x1800
        expectedSize: 0x800
      - fileName: pv05
        startAddr: 0x4000
        expectedSize: 0x800
    # Optional: PROMs containing color data, takes precedence on color overlays
    colorPROMs:
      - fileName: pv06.1
        expectedSize: 0x400
      - fileName: pv07.2
        expectedSize: 0x400

  spclaser:
    romParts:
      - fileName: la01
        startAddr: 0x0
        expectedSize: 0x800
      - fileName: la02
        startAddr: 0x800
        expectedSize: 0x800
      - fileName: la03
        startAddr: 0x1000
        expectedSize: 0x800
      - fileName: la04
        startAddr: 0x1800
        expectedSize: 0x800
    colorPROMs:
      - fileName: "01.1"
        expectedSize: 0x400
      - fileName: "02.2"
        expectedSize: 0x400

  ballbomb:
    romParts:
      - fileName: tn01
        startAddr: 0x0
        expectedSize: 0x800
      - fileName: tn02
        startAddr: 0x800
        expectedSize: 0x800
      - fileName: tn03
        startAddr: 0x1000
        expectedSize: 0x800
      - fileName: tn04
        startAddr: 0x1800
        expectedSize: 0x800
      - fileName: tn05-1
        startAddr: 0x4000
        expectedSize: 0x800
    colorPROMs:
      - fileName: tn06
        expectedSize: 0x400
      - fileName: tn07
        expectedSize: 0x400
